apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-tfpg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0050-tenant/tkrw-pr712-0075-0050-app/devfile-sample-tfpg@sha256:5eb380604e7085553e1e26d956eeb5ef84edd1d03afa039c1c7f69b56280ee4c
        name: my-nodejs
        resources: {}
status: {}
